# Generated by Django 3.2.9 on 2021-11-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20211111_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='post',
        ),
    ]
