# Generated by Django 3.2.9 on 2021-11-11 12:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_rename_image_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
