# Generated by Django 3.2.9 on 2021-11-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_view',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
